spring:
  application:
    name: cloud-base-web
  resources:
    static-locations: classpath:/static/
server:
  port: 8020
eureka:
  client:
    service-url:
      defaultZone : http://localhost:8000/eureka
sso:
  domain : http://local.joninfo.cn:8020/login.html
  appName : user-app
  appUrl : http://local.joninfo.cn:8020/index.html